name: Test

on:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "custom_components/pypowerwall/translations/**"
      - "requirements*.txt"
      - "pytest.ini"
      - "pyproject.toml"
      - ".github/workflows/test.yml"
  pull_request:
    paths:
      - "**.py"
      - "custom_components/pypowerwall/translations/**"
      - "requirements*.txt"
      - "pytest.ini"
      - "pyproject.toml"
      - ".github/workflows/test.yml"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - run: pip install -r requirements-dev.txt
      - run: python3 -m pytest
